spring.application.name=3_implementing_custom_csrf_token_repository_to_store_tokens_in_a_database
spring.datasource.url=jdbc:mysql://localhost/spring
spring.datasource.username=root
spring.datasource.password=Saikad@1234
spring.sql.init.mode=always