spring.application.name=1_using_csrf_token_to_make_post_request
#management.endpoints.web.exposure.include=sessions,health,info # Add other endpoints as needed
#management.endpoints.web.base-path=/actuator
management.endpoints.web.exposure.include=*