spring.application.name=3_filtering_data_returned_by_a_repository
spring.datasource.url=jdbc:mysql://localhost:3306/spring
spring.datasource.username=root
spring.datasource.password=Saikad@1234
spring.jpa.hibernate.ddl-auto=update